[project]
name = "cloudcruise"
version = "0.1.0"
description = "HAR file processing API with Kafka, S3/MinIO, PostgreSQL, and LLM-powered curl generation"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "python-multipart>=0.0.12",
    "boto3>=1.35.0",
    "sqlalchemy>=2.0.36",
    "psycopg2-binary>=2.9.10",
    "aiokafka>=0.11.0",
    "slowapi>=0.1.9",
    "redis>=5.2.0",
    "litellm>=1.55.0",
    "pydantic-settings>=2.6.0",
    "alembic>=1.14.0",
    "httpx>=0.27.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.0",
    "httpx>=0.27.0",
]
