"""Initial migration

Revision ID: 52e64059c12e
Revises: 
Create Date: 2025-10-02 21:21:24.745304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52e64059c12e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('har_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('user_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_har_files_id'), 'har_files', ['id'], unique=False)
    op.create_index(op.f('ix_har_files_job_id'), 'har_files', ['job_id'], unique=True)
    op.create_index(op.f('ix_har_files_status'), 'har_files', ['status'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('har_file_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('request_size', sa.BigInteger(), nullable=True),
    sa.Column('response_size', sa.BigInteger(), nullable=True),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['har_file_id'], ['har_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_domain_gin', 'requests', ['domain'], unique=False, postgresql_using='gin', postgresql_ops={'domain': 'gin_trgm_ops'})
    op.create_index('idx_request_path_gin', 'requests', ['path'], unique=False, postgresql_using='gin', postgresql_ops={'path': 'gin_trgm_ops'})
    op.create_index('idx_request_query_params_gin', 'requests', ['query_params'], unique=False, postgresql_using='gin')
    op.create_index('idx_request_url_gin', 'requests', ['url'], unique=False, postgresql_using='gin', postgresql_ops={'url': 'gin_trgm_ops'})
    op.create_index(op.f('ix_requests_content_type'), 'requests', ['content_type'], unique=False)
    op.create_index(op.f('ix_requests_domain'), 'requests', ['domain'], unique=False)
    op.create_index(op.f('ix_requests_har_file_id'), 'requests', ['har_file_id'], unique=False)
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_method'), 'requests', ['method'], unique=False)
    op.create_index(op.f('ix_requests_status_code'), 'requests', ['status_code'], unique=False)
    op.create_index(op.f('ix_requests_timestamp'), 'requests', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_timestamp'), table_name='requests')
    op.drop_index(op.f('ix_requests_status_code'), table_name='requests')
    op.drop_index(op.f('ix_requests_method'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_har_file_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_domain'), table_name='requests')
    op.drop_index(op.f('ix_requests_content_type'), table_name='requests')
    op.drop_index('idx_request_url_gin', table_name='requests', postgresql_using='gin', postgresql_ops={'url': 'gin_trgm_ops'})
    op.drop_index('idx_request_query_params_gin', table_name='requests', postgresql_using='gin')
    op.drop_index('idx_request_path_gin', table_name='requests', postgresql_using='gin', postgresql_ops={'path': 'gin_trgm_ops'})
    op.drop_index('idx_request_domain_gin', table_name='requests', postgresql_using='gin', postgresql_ops={'domain': 'gin_trgm_ops'})
    op.drop_table('requests')
    op.drop_index(op.f('ix_har_files_status'), table_name='har_files')
    op.drop_index(op.f('ix_har_files_job_id'), table_name='har_files')
    op.drop_index(op.f('ix_har_files_id'), table_name='har_files')
    op.drop_table('har_files')
    # ### end Alembic commands ###
